### ISSUE TITLE
Feature request: helper(s) to avoid syntax errors

### ISSUE THREAD

**Issue by craigds** [jreese/fissix#1]
(Not sure if this belongs in bowler or fissix)

I wrote a thing to convert `self.assertFalse(x)` to `assert not x`, etc. Trouble is, it falls over easily when the expression in the parentheses isn't valid without the parentheses:

```python
self.assertFalse(
    'a'
    'b'
)
```
My code naively converts this to

```python
assert not 'a'
    'b'
```

* I think a `parenthesize_if_necessary` helper would be really useful for this kind of situation. I imagine this bug is widespread. I tried to write one, but I'm a bit out of my depth.
* It'd be useful to have access to a function which asserts a list of nodes has no syntax errors. I realise that would vary depending on targeted python version and `__future__` imports, but perhaps something can be done? 

Thanks

**Comment by jreese** [comment]
I agree that these would be useful helpers/features to have, but I think they would belong more appropriately in [Bowler](https://github.com/facebookincubator/Bowler).  Fissix is just a backport of lib2to3, and as such, is not going to support any extra features or helpers.  I'd suggest opening this issue on Bowler instead, as we would really like to have better validation of results and improve usability of refactoring.
