### ISSUE TITLE
Parse error on argument called "print"

### ISSUE THREAD

**Issue by timokau** [jreese/fissix#2]
Related to this lib2to3 bug: https://bugs.python.org/issue35383

When having a kwarg called `print`, parsing fails. Minimal example:

```python
from fissix.pgen2.driver import Driver
from fissix import pytree
from fissix.pygram import python_grammar
import sys
d = Driver(grammar=python_grammar, convert=pytree.convert)
d.parse_string('print("a", file=sys.stderr)')
```

Results in:

```
ParseError                                Traceback (most recent call last)
<ipython-input-1-617e4f2e4fd8> in <module>
      4 import sys
      5 d = Driver(grammar=python_grammar, convert=pytree.convert)
----> 6 d.parse_string('print("a", file=sys.stderr)')

/nix/store/qh5vvjgvs792gb67k5aywndqrkgp3j2w-python3-3.7.2-env/lib/python3.7/site-packages/fissix/pgen2/driver.py in parse_string(self, text, debug)
    101         """Parse a string and return the syntax tree."""
    102         tokens = tokenize.generate_tokens(io.StringIO(text).readline)
--> 103         return self.parse_tokens(tokens, debug)
    104 
    105 

/nix/store/qh5vvjgvs792gb67k5aywndqrkgp3j2w-python3-3.7.2-env/lib/python3.7/site-packages/fissix/pgen2/driver.py in parse_tokens(self, tokens, debug)
     70                     "%s %r (prefix=%r)", token.tok_name[type], value, prefix
     71                 )
---> 72             if p.addtoken(type, value, (prefix, start)):
     73                 if debug:
     74                     self.logger.debug("Stop.")

/nix/store/qh5vvjgvs792gb67k5aywndqrkgp3j2w-python3-3.7.2-env/lib/python3.7/site-packages/fissix/pgen2/parse.py in addtoken(self, type, value, context)
    159                 else:
    160                     # No success finding a transition
--> 161                     raise ParseError("bad input", type, value, context)
    162 
    163     def classify(self, type, value, context):

ParseError: bad input: type=22, value='=', context=('', (1, 15))
```

**Comment by jreese** [comment]
Use `from fissix.pygram import python_grammar_no_print_statement` if you wish to parse code without treating `print` as a reserved keyword.

**Comment by timokau** [comment]
Same result:

```
In [1]: from fissix.pgen2.driver import Driver 
   ...: from fissix import pytree 
   ...: from fissix.pygram import python_grammar_no_print_statement 
   ...: import sys 
   ...: d = Driver(grammar=python_grammar_no_print_statement, convert=pytree.convert) 
   ...: d.parse_string('print("a", file=sys.stderr)')                                                                                
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
<ipython-input-1-aa448e807bd0> in <module>
      4 import sys
      5 d = Driver(grammar=python_grammar_no_print_statement, convert=pytree.convert)
----> 6 d.parse_string('print("a", file=sys.stderr)')

/nix/store/qh5vvjgvs792gb67k5aywndqrkgp3j2w-python3-3.7.2-env/lib/python3.7/site-packages/fissix/pgen2/driver.py in parse_string(self, text, debug)
    101         """Parse a string and return the syntax tree."""
    102         tokens = tokenize.generate_tokens(io.StringIO(text).readline)
--> 103         return self.parse_tokens(tokens, debug)
    104 
    105 

/nix/store/qh5vvjgvs792gb67k5aywndqrkgp3j2w-python3-3.7.2-env/lib/python3.7/site-packages/fissix/pgen2/driver.py in parse_tokens(self, tokens, debug)
     70                     "%s %r (prefix=%r)", token.tok_name[type], value, prefix
     71                 )
---> 72             if p.addtoken(type, value, (prefix, start)):
     73                 if debug:
     74                     self.logger.debug("Stop.")

/nix/store/qh5vvjgvs792gb67k5aywndqrkgp3j2w-python3-3.7.2-env/lib/python3.7/site-packages/fissix/pgen2/parse.py in addtoken(self, type, value, context)
    159                 else:
    160                     # No success finding a transition
--> 161                     raise ParseError("bad input", type, value, context)
    162 
    163     def classify(self, type, value, context):

ParseError: bad input: type=0, value='', context=('\n', (2, 0))
```

**Comment by jreese** [comment]
That is actually a different errror.  Your input string is invalid (no trailing newline).

**Comment by timokau** [comment]
Oh, you're right. Thanks.

Still, shouldn't `python_grammar_no_print_statement` be discovered based on weather or not `from __future__ import print_statement` is present?

**Comment by jreese** [comment]
Ideally, that would be the case, but that feature should be submitted to the CPython/lib2to3 project/tracker.  Fissix is just a backport of lib2to3 from master – it does not include any extra features.

**Comment by timokau** [comment]
It is, that is the python bug I linked to. Its "wontfix"ed for now. I asked here because of the "with enhancements" in the tagline, but I get that you don't want to put too much into implementing usecases that aren't your own.

Thanks for your help so far and your work on fissix/Bowler :)

**Comment by jreese** [comment]
I'm more concerned about not making it too difficult to continue merging changes from upstream - as is, most of the "enhancements" are small, one off changes rather than features, or replicable from upstream like formatting.  I may consider adding more in the future if there is a good way to cleanly separate them and prevent merge conflicts, but would obviously prefer making those changes upstream.  

That said, the driver class in lib2to3 probably isn't the place to make that change, as it just loads the static grammars, and shouldn't have to care about file contents. The refactoring tool class is where lib2to3 puts the feature to choose which grammar is used, but obviously that makes the choice for all files it modifies rather than when modifying each file.  If there was an easy way to make that distinction per file, and was submitted as a feature request on BPO or a PR to CPython, then it's quite possible that it would be approved, or at least open up a discussion on where the correct place would be to put that feature.

**Comment by timokau** [comment]
> I'm more concerned about not making it too difficult to continue merging changes from upstream

Understandable.

> That said, the driver class in lib2to3 probably isn't the place to make that change, as it just loads the static grammars, and shouldn't have to care about file contents

But I think it has to. Due to the nature of `__future__` imports, the grammar may change during parsing. Its ugly and breaks the traditional separation of concerns, but that is the way it is designed.

Anyway I was able to solve my problem with a mix of plain `ast` to find the location and then manual editing. It isn't as pretty as lib2to3, but using `ast` should be much more reliable and its actually simpler for my simple usecase. So I'm not that heavily invested anymore.

Thanks again for considering :)
