### ISSUE TITLE
upload docs to rtfd etc

### ISSUE THREAD

**Issue by graingert** [jreese/fissix#23]
### Description
I'd like to link from https://modernize.readthedocs.io/en/latest/fixers.html#to3-fixers to fissix but there's no docs page on https://fissix.readthedocs.io/

**Comment by jreese** [comment]
What documentation are you wanting/expecting to see? Just generated autodocs, or are you looking for a duplicate of the cpython docs you already link to?

**Comment by graingert** [comment]
@jreese mostly a duplicate, but with lib2to3 swapped out for fissix, etc.

**Comment by graingert** [comment]
and if fixes start getting added here, the docs would need to be updated here too

**Comment by jreese** [comment]
https://fissix.readthedocs.io/en/latest/
