### ISSUE TITLE
Please make fissix/tests relocatable and able to load from system libs rather than source tree

### ISSUE THREAD

**Issue by sten0** [jreese/fissix#30]
### Description

Please make fissix/tests relocatable and able to load from system libs rather than source tree.  This is required for Debian's CI, because we must test packages as-installed rather than from their source trees.  Additionally, we're supposed to load libs and modules from their build directory rather than from the source repo during the initial build.  Setting and exporting `PYTHONPATH` has no effect on this issue at present (a67281e).  Ideally it would be nice to be able to skip the loading of a helper script that sets up the existing strict load-from-source-tree expectation.

### Details

* OS: Debian sid (currently 11)
* Python version: 3.9.0
* fissix version: v20.8.0
* Can you repro on master? v20.8.0-15-ga67281e (a67281e) does not appear to contain commits that would allow successful execution of self-tests on our infrastructure.
* Can you repro in a clean virtualenv? NA

Thank you for your consideration,
Nicholas

**Comment by graingert** [comment]
@sten0 does `python -m pytest --verbose tests fissix/tests` work for you?
